export type LSystemPresetId =
  | "koch-snowflake"
  | "sierpinski-triangle"
  | "sierpinski-arrowhead"
  | "dragon-curve"
  | "fractal-plant"
  | "hilbert-curve";

export interface LSystemPreset {
  id: LSystemPresetId;
  name: string;
  description: string;
  axiom: string;
  rules: Record<string, string>;
  angle: number;
  startAngle: number;
  drawChars: string[];
  defaultIterations: number;
  maxIterations: number;
}

export const LSYSTEM_PRESETS: Record<LSystemPresetId, LSystemPreset> = {
  "koch-snowflake": {
    id: "koch-snowflake",
    name: "Koch Snowflake",
    description: "Three Koch curves joined into a snowflake outline.",
    axiom: "F++F++F",
    rules: { F: "F-F++F-F" },
    angle: 60,
    startAngle: 0,
    drawChars: ["F"],
    defaultIterations: 3,
    maxIterations: 6,
  },
  "sierpinski-triangle": {
    id: "sierpinski-triangle",
    name: "Sierpinski Triangle",
    description: "Classic triangle fractal built from two edge rules.",
    axiom: "F-G-G",
    rules: { F: "F-G+F+G-F", G: "GG" },
    angle: 120,
    startAngle: 0,
    drawChars: ["F", "G"],
    defaultIterations: 4,
    maxIterations: 7,
  },
  "sierpinski-arrowhead": {
    id: "sierpinski-arrowhead",
    name: "Sierpinski Arrowhead",
    description: "Space-filling variant that traces the triangle in one stroke.",
    axiom: "A",
    rules: { A: "B-A-B", B: "A+B+A" },
    angle: 60,
    startAngle: 0,
    drawChars: ["A", "B"],
    defaultIterations: 5,
    maxIterations: 8,
  },
  "dragon-curve": {
    id: "dragon-curve",
    name: "L-System Dragon Curve",
    description: "Paper-folding dragon curve generated by string rewriting.",
    axiom: "FX",
    rules: { X: "X+YF+", Y: "-FX-Y" },
    angle: 90,
    startAngle: 0,
    drawChars: ["F"],
    defaultIterations: 9,
    maxIterations: 15,
  },
  "fractal-plant": {
    id: "fractal-plant",
    name: "Fractal Plant",
    description: "Lindenmayer's branching plant with a push/pop stack.",
    axiom: "X",
    rules: { X: "F+[[X]-X]-F[-FX]+X", F: "FF" },
    angle: 25,
    startAngle: -90,
    drawChars: ["F"],
    defaultIterations: 5,
    maxIterations: 7,
  },
  "hilbert-curve": {
    id: "hilbert-curve",
    name: "Hilbert Curve",
    description: "Space-filling curve that covers a square without crossing itself.",
    axiom: "A",
    rules: { A: "-BF+AFA+FB-", B: "+AF-BFB-FA+" },
    angle: 90,
    startAngle: 0,
    drawChars: ["F"],
    defaultIterations: 5,
    maxIterations: 7,
  },
};

export function clampLSystemIterations(
  presetId: LSystemPresetId,
  value: number
): number {
  const preset = LSYSTEM_PRESETS[presetId];
  if (!Number.isFinite(value)) {
    return preset.defaultIterations;
  }
  return Math.min(preset.maxIterations, Math.max(0, Math.round(value)));
}

export function expandLSystem(
  axiom: string,
  rules: Record<string, string>,
  iterations: number
): string {
  let current = axiom;
  for (let i = 0; i < iterations; i++) {
    let next = "";
    for (const ch of current) {
      next += rules[ch] ?? ch;
    }
    current = next;
  }
  return current;
}

export interface LSystemSegment {
  x1: number;
  y1: number;
  x2: number;
  y2: number;
}

export function interpretLSystem(
  commands: string,
  angleDeg: number,
  startAngleDeg: number,
  drawChars: string[]
): LSystemSegment[] {
  const drawSet = new Set(drawChars);
  const segments: LSystemSegment[] = [];
  let x = 0;
  let y = 0;
  let angle = startAngleDeg;
  const stack: { x: number; y: number; angle: number }[] = [];

  for (const ch of commands) {
    if (drawSet.has(ch)) {
      const rad = (angle * Math.PI) / 180;
      const nx = x + Math.cos(rad);
      const ny = y + Math.sin(rad);
      segments.push({ x1: x, y1: y, x2: nx, y2: ny });
      x = nx;
      y = ny;
    } else if (ch === "f") {
      const rad = (angle * Math.PI) / 180;
      x += Math.cos(rad);
      y += Math.sin(rad);
    } else if (ch === "+") {
      angle += angleDeg;
    } else if (ch === "-") {
      angle -= angleDeg;
    } else if (ch === "[") {
      stack.push({ x, y, angle });
    } else if (ch === "]") {
      const state = stack.pop();
      if (state) {
        x = state.x;
        y = state.y;
        angle = state.angle;
      }
    }
  }

  return segments;
}

export interface LSystemBounds {
  minX: number;
  minY: number;
  maxX: number;
  maxY: number;
}

export function boundsOfSegments(segments: LSystemSegment[]): LSystemBounds {
  if (segments.length === 0) {
    return { minX: 0, minY: 0, maxX: 1, maxY: 1 };
  }

  let minX = Infinity;
  let minY = Infinity;
  let maxX = -Infinity;
  let maxY = -Infinity;

  for (const seg of segments) {
    minX = Math.min(minX, seg.x1, seg.x2);
    minY = Math.min(minY, seg.y1, seg.y2);
    maxX = Math.max(maxX, seg.x1, seg.x2);
    maxY = Math.max(maxY, seg.y1, seg.y2);
  }

  return { minX, minY, maxX, maxY };
}

export function fitSegmentsToViewport(
  segments: LSystemSegment[],
  width: number,
  height: number,
  padding: number
): LSystemSegment[] {
  const bounds = boundsOfSegments(segments);
  const spanX = Math.max(bounds.maxX - bounds.minX, 1e-9);
  const spanY = Math.max(bounds.maxY - bounds.minY, 1e-9);
  const availableW = Math.max(width - padding * 2, 1);
  const availableH = Math.max(height - padding * 2, 1);
  const scale = Math.min(availableW / spanX, availableH / spanY);
  const offsetX =
    padding + (availableW - spanX * scale) / 2 - bounds.minX * scale;
  const offsetY =
    padding + (availableH - spanY * scale) / 2 - bounds.minY * scale;

  return segments.map((seg) => ({
    x1: seg.x1 * scale + offsetX,
    y1: height - (seg.y1 * scale + offsetY),
    x2: seg.x2 * scale + offsetX,
    y2: height - (seg.y2 * scale + offsetY),
  }));
}

export function buildLSystemSegments(
  presetId: LSystemPresetId,
  iterations: number
): LSystemSegment[] {
  const preset = LSYSTEM_PRESETS[presetId];
  const clamped = clampLSystemIterations(presetId, iterations);
  const commands = expandLSystem(preset.axiom, preset.rules, clamped);
  return interpretLSystem(
    commands,
    preset.angle,
    preset.startAngle,
    preset.drawChars
  );
}
